### ISSUE TITLE
Investigate ore distribution on overworld - skewed towards higher percentage ores

### ISSUE THREAD

**Issue by richardhendricks** [richardhendricks/GT5-Unofficial#13]
Working ticket for https://github.com/GTNewHorizons/NewHorizons/issues/2302

**Comment by WarlordWossman** [comment]
Strange, but I always felt like the ratios were off. I stoped playing on one SSP world because 11/16 veins in the twilight were limonite.

**Comment by richardhendricks** [comment]
deleted, incorrect

**Comment by richardhendricks** [comment]
9445 total weight on current build

**Comment by richardhendricks** [comment]
Something is wrong with XSTR implementation in Minecraft.
Did a test using Java Random(), XSTR class on my PC standalone, and from Minecraft. Minecraft shows much higher variance up and down than either Java or XSTR implemented standalone.
![image](https://user-images.githubusercontent.com/1214811/34914666-71705ef6-f8dc-11e7-98f5-5a77c72cfc91.png)

![image](https://user-images.githubusercontent.com/1214811/34914667-799e083a-f8dc-11e7-8766-8ed5d0c78887.png)

![image](https://user-images.githubusercontent.com/1214811/34914676-b3f4ff16-f8dc-11e7-9c3d-06590a9f7854.png)

These are bins of 20. You can see that the MC GT XSTR data has more spikes and valleys than the other two.  Something is causing the MC GT XSTR to skew. More testing needed.

**Comment by richardhendricks** [comment]
POR:
1. Try changing to Java Random() class.
2. Adjust orevein placement so if it fails due to too high, it tries again a few times before trying a new ore.
3. Adjust heights so that rare veins are Y less than average (more likely to place) and really common veins can be higher altitude.
4. Maybe mess with mountain veins 60+ Y min so that they aren't always placed in air - maybe lower their max height so they are more likely to successfully spawn

**Comment by richardhendricks** [comment]
OK, random was a red herring, it was not the cause.

The cause for the bias is that the way the original algorithm worked is that if an orevein did not reach this chunk, it tried for another orevein.  This caused a major bias towards the larger oreveins.  That option has been modified, if an orevein does not reach this chunk, and this chunk has a replaceable block at its center at the Y height of the bottom of the orevein, the orevein is saved to the list. This way even small veins will be saved to the list and used later when chunks closer to the center of it are populated.

Done some testing in a limited environment, apatite and diamond amounts are right where expected. Will do some more testing and push an update.

**Comment by richardhendricks** [comment]
PR filed, closing ticket.
