### ISSUE TITLE
Evaluate GT Ore NEI plugin options

### ISSUE THREAD

**Issue by richardhendricks** [richardhendricks/GT5-Unofficial#15]
https://github.com/GTNewHorizons/NewHorizons/issues/2427

https://github.com/GTNewHorizons/NewHorizons/issues/2423

**Comment by bartimaeusnek** [comment]
well i fixed the %material issure, but the dimension issure tho, for 
[2427](https://github.com/GTNewHorizons/NewHorizons/issues/2427)

**Comment by richardhendricks** [comment]
Look at having ore NEI plugin print out orevein information for spreadsheet.
