### ISSUE TITLE
Add to BQ a block that you can hit to do the magic stuff to reload your questbook.

### ISSUE THREAD

**Issue by richardhendricks** [richardhendricks/GT5-Unofficial#16]
Reload quest book, save to backup, restore from backup

**Comment by richardhendricks** [comment]
https://github.com/GTNewHorizons/NewHorizons/issues/1611

**Comment by WarlordWossman** [comment]
- should be a quest reward early on
- should also be craftable from the beginning with easy recipe (if you happen to lose it for whatever reason)

**Comment by bartimaeusnek** [comment]
actually that was a joke, but okay youre free to add this... 😸 
EDIT:  @WarlordWossman Should be SSP only
EDIT2: https://github.com/LOKKO12/BetterQuesting made one, but it can only reload
EDIT3: [See here](https://github.com/GTNewHorizons/NewHorizons/issues/1611#issuecomment-358971463)

**Comment by richardhendricks** [comment]
Yeah, I can see why it should be SSP only.  Server admins should handle it there.  It would be nice to make a backup of the questbooks, but that's not something that should be done locally with servers, be too easy to cheat on that.
