### ISSUE TITLE
Make "Learn NEI" quests

### ISSUE THREAD

**Issue by richardhendricks** [richardhendricks/GT5-Unofficial#19]
How many HV cable types are there? Submit circuit with answer

**Comment by richardhendricks** [comment]
@mod
@mod.gt++

**Comment by richardhendricks** [comment]
Using T to search nearby inventories
double-clicking the text window to find objects in your inventory

**Comment by richardhendricks** [comment]
making the window disappear/reapper

**Comment by richardhendricks** [comment]
#oredict name
#dyeBlue

**Comment by richardhendricks** [comment]
O key - hides UI when looking at inventories

**Comment by Snaggerr** [comment]
Lesson 1: left-click or press "R" for recipe, right-click or press "U" for used in. Backspace to go back 1 recipe.
Lesson 2: Search bar.  Right-click to clear, double-click to highlight matching items.  "T" to search nearby inventories.
Lesson 3: Subsets. Click the subsets dropdown bar at the top and double-left click a mod in the list to "solo" and filter out all other mods, then single-left click the "mods" subcategory to remove all filters.
Lesson 4: Vein data.  Show how to look up data by pressing "U" or right-clicking on a raw ore, then click "See All" to browse vein data.  Do the same thing for the fuel values data.

It might be helpful to also teach new users about how veins and ore mixes work at the same time as introducing the NEI data.  Give them some hands-on experience on how to locate a vein by searching in the correct height, dimension, etc.
