### ISSUE TITLE
Look into making hardened clay a potential target for oregen

### ISSUE THREAD

**Issue by richardhendricks** [richardhendricks/GT5-Unofficial#5]
Simple way, replace hardened clay with a stone block of the ore type

Complex way, make new blocks and meta IDs for hardened clay ores.

**Comment by WarlordWossman** [comment]
I know this is still just a concept but if there were clay types it could be cool to have a different macerator duration and some other behaviors in general so it's not just "clay instead of stone" but also feels different when put into certain machines.

**Comment by richardhendricks** [comment]
Other ideas - 

Sand as an ore target for "sand" based ores

Make sandy ores break as crushed ores so fortune digging tools benefit

Clay ores - need some ideas on distinguishing them.  orewashing maybe gives nuggets? (imagine the uproar!) and clay instead of just clay dust?  Perhaps make them easier/faster to macerate & wash since they aren't solid rock?

**Comment by draknyte1** [comment]
Make them worth Small dusts and then have them break like small ores.
>Makes Fortune worth something.
>Can be mined with a shovel quickly.
>Veins make sense being thinner but larger. (2-4 high, but lignite size x/y wise)
